### ISSUE TITLE
Suggestion: Add Websockets support

### ISSUE THREAD

**Issue by sbrl** [rosenbjerg/RHttpServer.CSharp#2]
It would make the development of multi-user interactive experiences much easier, as I wouldn't have to have both a websocket server and a regular http server running on different ports.

Perhaps it could be done via a plugin?

**Comment by rosenbjerg** [comment]
Good idea. i've thought about implementing something for websockets a couple of times, but other things seems to have been more appealing to work at. Do you have any suggestions for the use-pattern? some pseudocode of how you would expect the api to be will be appreciated.

**Comment by sbrl** [comment]
Hrm. I'm not sure. I'm not sure how to use `RHttpServer` in the first place. Looking at your example code, perhaps something like this would work?:

```csharp
List<WebSocketClient> clientList = new List<WebSocketClient>();
RHttpServer server = new RHttpServer.HttpServer(3000, 4, "./public");
server.Websocket("/endpoint", (WebSocketClient client) => {
  if(clientIsOk) {
    client.OnMessage += SomeMethod;
    clientList.Add(client);
  }
  else {
    return false;
  }
});

// Regular http stuff....!
server.Get("/", (req, res) =>
{
    res.SendString("Welcome");
});

server.Start(true);
```

What do you think? :smiley:

**Comment by sbrl** [comment]
@rosenbjerg Ummm you closed this? A reason would be nice 😕

**Comment by githuis** [comment]
Pretty sure he implemented it. 
[Websockets](https://github.com/rosenbjerg/RHttpServer.CSharp/commit/a4f8bc03c95a5e670fbbff301aabde1bb818bcf0)

**Comment by rosenbjerg** [comment]
@sbrl The reason for closing this, is that it is now implemented :)

**Comment by sbrl** [comment]
@rosenbjerg Awesome~! I've (just!) gotten around to properly checking it out as a replacement to `IotWeb`, since I've been having some issues with it throwing exceptions. Unfortunately, I'm on linux, and you've used `HttpListenerWebSocketContext`, which your docs specifically mention isn't implemented in mono, so I can't use it :confused:

Is there a PR I could send to bypass this restriction and use it with mono?

**Comment by sbrl** [comment]
Hrm. I theorise that it might actually work with the shipping of mono 5 - which uses the microsoft csc compiler on linux.

Also, I've noticed that you use a `HttpListener` underneath. Does this mean that `RedHttpServer` requires admin rights on windows?

**Comment by rosenbjerg** [comment]
@sbrl Yeah, Mono does not support the WebSockets used in HttpListener. That is why i made a new version based on .NET Core, so it can run natively on linux with WebSocket support. If you look on the front page of this repo, there is a link to the new repo

**Comment by sbrl** [comment]
@rosenbjerg Ah, cool. So does that mean that I need the new `dotnet` thingy for linux to use .NET core, then? Or does mono have support for it

**Comment by rosenbjerg** [comment]
@sbrl Yes it does. As I mentioned, Mono does not support WebSockets, so if you need them on linux, you will need to use .NET Core
